version: "3.8"
volumes:
  db-store:
  node_modules-store:
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /backend
      - type: volume
        source: node_modules-store
        target: /backend/node_modules
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    tty: true
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_USER=nest
      - MYSQL_PASSWORD=nest
      - MYSQL_ROOT_PASSWORD=nest
